### ISSUE TITLE
Text in tag pane for the front matter in dark mode not very visible

### ISSUE THREAD

**Issue by AvijeetPrasad** [Mara-Li/Obsidian-Snippet-collection#1]
Hi,
I am using the Yin-Yang theme in the dark mode. I noticed that the background for the tag pane in the front matter in dark mode is not very visible. Please see the attached screenshot. Can you suggest any changes to resolve this?

![image](https://user-images.githubusercontent.com/45669486/122259996-63399100-ce98-11eb-8494-258221a6c21d.png)

Thanks!

**Comment by Mara-Li** [comment]
Oh, I forgot to add the style settings to do that! I will update it soon thanks :)

**Comment by Mara-Li** [comment]
Do you have style settings ? Because there is option to change all !
![image](https://user-images.githubusercontent.com/30244939/122268337-3c04b300-cedc-11eb-8b21-25eb87d877ba.png)

Also, I check the plugin in a blank vault and the color edit work at 100%.
