### ISSUE TITLE
Snippet for folder icons = 404

### ISSUE THREAD

**Issue by DutchPete** [Mara-Li/Obsidian-Snippet-collection#5]
Clicking on the link leads to a 404 page.

**Comment by Mara-Li** [comment]
[are you sure ?](https://github.com/Mara-Li/Obsidian-Snippet-collection/blob/main/folders.icon.font.css)

**Comment by Larandar** [comment]
They meant [In the README: the `this snippets`](https://github.com/Mara-Li/Obsidian-Snippet-collection#folder-icons) that does not use the new name

**Comment by DutchPete** [comment]
@Mara-Li : @Larandar is right. And the link you provided shows this

![image](https://user-images.githubusercontent.com/10794265/130340044-9e3bf8cd-5d2e-4a97-a697-0704f21afe7a.png)


So, still no folder icons snippet.

**Comment by Mara-Li** [comment]
> @Mara-Li : @Larandar is right. And the link you provided shows this
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10794265/130340044-9e3bf8cd-5d2e-4a97-a697-0704f21afe7a.png)
> 
> 
> 
> 
> 
> So, still no folder icons snippet.

It's normal. The snippet is pretty big because I embed font in it. You need to download it. You can also download all the repo or take the asset in release.

For the moment, the auto release action doesn't give directly the files, for a reason I can't understand.

**Comment by Mara-Li** [comment]
> They meant [In the README: the `this snippets`](https://github.com/Mara-Li/Obsidian-Snippet-collection#folder-icons) that does not use the new name

Thanks, I will update it asap

**Comment by Mara-Li** [comment]
Have you success to download all the file ?

**Comment by DutchPete** [comment]
@Mara-Li : no, I did not manage it. When I click on the `download` button I get to a webpage with that very long list of boxicon URLs, but nothing is downloaded.

Of course I could copy all that and paste into a css file.

**Comment by Mara-Li** [comment]
> @Mara-Li : no, I did not manage it. When I click on the `download` button I get to a webpage with that very long list of boxicon URLs, but nothing is downloaded.
> 
> 
> 
> Of course I could copy all that and paste into a css file.

Yeah it's normal ! You need to right click and save as...
I think that with the release asset (or download the entire repos) could work !

For a strange reason the auto release doesn't take the css so...
