### ISSUE TITLE
Question: How do you find the content values for the icon fonts?

### ISSUE THREAD

**Issue by wychwitch** [Mara-Li/Obsidian-Snippet-collection#6]
Hello!! I'm just getting started using the colored folder and folder Icons and its fantastic! However I'm running into a bit of a brick wall. How do you find the content values for the icons in the `folders.icon.font.css` file? This may be a dumb question, but I've been trying and haven't been able to reliably select new custom icons because the values are seemingly random codes.

Thank you very much in advance, I'm very new to CSS so I hope you'll bear with me ^^

**Comment by Mara-Li** [comment]
Hello ! 
Sorry I didn't have any notification at all on github… 

So, for any future people here, if you need to get the code point :
![image](https://user-images.githubusercontent.com/30244939/139921566-13c021c8-d1b8-4f3d-ba61-db7c1306a771.png)[Font Awesome](https://fontawesome.com/) : Just search your icon, and copy the code as `\f02b`. Replace it in your snippet or in the Style settings plugin. (Note : I include Free, Free Solid, and Brands)
![image](https://user-images.githubusercontent.com/30244939/139920174-299d4120-6594-4adc-b0f9-4b956858401e.png)

![image](https://user-images.githubusercontent.com/30244939/139921571-3c73fa57-4512-4cdd-aba7-abf8a3f7f6fe.png)[Material Icons](https://fonts.google.com/) : Search your icons and click on "code point" (as '\e2c7`). 
![image](https://user-images.githubusercontent.com/30244939/139920478-7419138c-17f7-4ae7-8891-fca2ffc1e613.png)

- [IconMoon Free](https://icomoon.io/app/#/select) : Search and select your icons, Click on generate font and you will can copy the code point
![image](https://user-images.githubusercontent.com/30244939/139920626-1179689f-c362-46ba-a4ca-fe9eef2a1ae7.png)

Remixicon and boxicon are pretty tricky to get the code point at this point.

- [Remixicons](https://remixicon.com/) look for the icon you want. Press F12 (developer panel) and click on the icon. You will get something like `.ri-home-3-line::before` and you can get the code point here (in `content`).
![image](https://user-images.githubusercontent.com/30244939/139921579-256501a6-890f-4db4-bf63-bdb25ce7bf8d.png)

- [Boxicons](https://boxicons.com/) : Same as above
![image](https://user-images.githubusercontent.com/30244939/139922065-8cc522d7-00c4-47bf-a782-c52ae59be659.png)

Alternatively, you can check the github with the name of the icon (as `re-something` and `box-something`)

**Comment by wychwitch** [comment]
THANK YOU SO MUCH THIS IS INCREDIBLY HELPFUL;;; and thank you so much for the screenshots too!!!
