### ISSUE TITLE
Trying to install on ipad

### ISSUE THREAD

**Issue by rmchale** [Mara-Li/Obsidian-Snippet-collection#7]
Are there different instructions for the ipad? 
```
Clone this repository in your .obsidian/snippet
Move .git, and wysiwyg.css snippet in your folder.
Delete the Obsidian-WYSIWYG folder.
```

Step #2 I am little confiused

Step to is `mv ~/.obsidian/snippet/Obsidian-Snippet-collection/.git <my-vault>`?  This seems odd to me.

**Comment by Mara-Li** [comment]
Well, on Ipad, it's a little tricky. Are you ready ? :D

First, please, download `a-shell` ! You can use `a-shell` mini, or any terminal app.

First, please, [follow the tutorial here](https://forum.obsidian.md/t/mobile-ios-app-to-work-with-hidden-folder/25741/2).

After, you get the access to your `.obsidian` !

When you are in `.obsidian`, copy all the content of the file you want.

After : 
1. `vim snippet_name.css`
2. click (? touch ? Press) your `i` key.
3. Paste the content 
4. Press `:` key, write `wq`.

You have now a snippet !

*I prefer to avoid using git and sync in my Ipad*

Also, I work on a snippet with A-shell to copy/paste css snippet and theme (plugin have now BRAT sooo).
