### ISSUE TITLE
[BUG] Incorrect Obsidian snippets folder shown in README.md

### ISSUE THREAD

**Issue by PJC-64** [Mara-Li/Obsidian-Snippet-collection#8]
**Describe the bug**
README.md shows the snippets folder as `snippet` when it should be `snippets`.  In other words, the CSS files need to be copied to `<vault>/.obsidian/snippets`, not `<vault>/.obsidian/snippet`

**To Reproduce**
N/A

**Screenshots**
N/A

**Platform (please complete the following information):**
All.

**Additional context**
N/A

**Comment by Mara-Li** [comment]
Good catch !
