### ISSUE TITLE
I don't understand how to use the icon in folders and files

### ISSUE THREAD

**Issue by MGriot** [Mara-Li/Obsidian-Snippet-collection#9]
Sorry, I'm probably stupid but I don't understand how to use icons in folders and files. Can you give me a tip?

**Comment by Mara-Li** [comment]
Using folder icons and some settings. Simply :)

**Comment by claremacrae** [comment]
Wow. Saying “simply” or “just” to someone who has said they don’t understand something is rarely helpful.

I would suggest reopening this, to at least allow someone  else who understands the project to try and give a kinder and more informative answer.

**Comment by Mara-Li** [comment]
It's
Litterally 
The name of the plugin

There are links in the readme ??
